plugins {
    id 'com.android.application'
}

android {
    namespace 'br.com.scanvag'
    compileSdk 33

    defaultConfig {
        applicationId 'br.com.scanvag'
        minSdk 23
        targetSdk 33
        versionCode 120
        versionName '1.2.0-coding-beta'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}
